### ISSUE TITLE
Unable to download model

### ISSUE THREAD

**Issue by EricTheGamer911** [1337ad/sketchrip#1]
Hi, there is no download button, tried both in chrome and firefox

**Comment by gurkenjaeger13** [comment]
Same for me, also tried Chrome + Firefox and also different models (even ones you can download natively).

**Comment by 1337ad** [comment]
Changes I just merged may fix this. Don't have time to test, but you're welcome to give it a shot.

**Comment by okh-mzny** [comment]
For me there are TWO Download buttons that both do not work in firefox (the model doesn't load in firefox, even without the userscript running).

In chromium there isn't one, and the model loads fine. The userscript only initializes in console and doesnt actually add a button.

Using the latest version.

**Comment by segant08** [comment]
its giving obj is undefined error in `    window.drawhook = function(obj) {
        if(obj._faked != true) {
            obj._faked = true;
            window.allmodel.push(obj)
            console.log(obj);
        }
    }`

**Comment by 1337ad** [comment]
Did some debugging, wrote a statement in the readme. This goes beyond the time I have available at the moment. Sorry everybody.
